default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: promptshare_development

test:
  <<: *default
  database: promptshare_test

production:
  <<: *default
  database: promptshare_production
  username: promptshare
  password: <%= ENV['PROMPTSHARE_DATABASE_PASSWORD'] %>

